# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:


    - task: ArtifactoryBuildPromotion@1
      inputs:
        artifactoryService: 'Artifactory'
        buildName: 'test'
        buildNumber: '1'
        targetRepo: 'resolve_to'
        status: 'Released'
        comment: 'yeah'
        sourceRepo: 'default-docker-local'
        includeDependencies: false
        copy: true
        dryRun: false