repoPath: jfrog/jfrog-pipelines-go-Sample     # replace jfrog with your username or org name
gitProvider: myGithub           # replace with your GitRepo integration name
artifactory: myArtifactory      # replace with your Artifactory integration name
